### ISSUE TITLE
Frontend Javascript Placement

### ISSUE THREAD

**Issue by PancakeAstronaut** [PancakeAstronaut/AmphenolICC#21]
Javascript on files in the frontend directory is fine and contains no code errors to my knowledge. However, Please migrate the code to external JS files in the Javascript directory. If the JS on the page is page specific, Make a comment in the code to denote it as such and include that in a comment as your reason when you close the ticket. Please read Label Descriptions for more information.

**Comment by nimeshsilva1997** [comment]
Does this work?

![image](https://user-images.githubusercontent.com/34174281/77372763-d3607200-6d3c-11ea-8358-4d78203750bb.png)
![image](https://user-images.githubusercontent.com/34174281/77372778-dfe4ca80-6d3c-11ea-9a5a-697147a8c13b.png)

**Comment by PancakeAstronaut** [comment]
Issue Resolved
